#!/usr/bin/env bash
# This is a bash script that transfers a file from a client to a server using scp

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
    # scp -o StrictHostKeyChecking=no some_page.html ubuntu@52.201.190.114:~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
    # scp -i ~/.ssh/school -o StrictHostKeyChecking=no some_page.html ubuntu@52.201.190.114:~/
fi
