#!/usr/bin/env bash
# script that displays the visitor IP along with the HTTP status code from the Apache log file.
# Format: IP HTTP_CODE 		in a list format

awk '{ print $1,$9 }' apache-access.log | sort | uniq -c | sort -rn
