#!/usr/bin/env bash
# script that groups visitors by IP and HTTP status code, and displays this data.
# The exact format must be: OCCURENCE_NUMBER IP HTTP_CODE
# Ordered from the greatest to the lowest number of occurrences

awk '{ print $1,$9 }' apache-access.log | sort | uniq -c | sort -nr
